from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO
import requests
from datetime import datetime

from schemas.save_prediction_schema import SavePredictionRequest

router = APIRouter(prefix="/report")

def download_image(url: str):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return BytesIO(response.content)
    except:
        pass
    return None

@router.post("/generate")
def generate_report(data: SavePredictionRequest):
    buffer = BytesIO()
    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=(595, 842),  # A4
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    elements = []

    # Title
    elements.append(Paragraph("Ophthalmology Screening Report", styles["Title"]))
    elements.append(Spacer(1, 20))

    # Patient info
    patient_table_data = [
        ["Patient Name", data.patient_name],
        ["Patient ID", data.patient_id or "N/A"],
        ["Doctor ID", data.doctor_id],
        ["Generated On", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")]
    ]

    table = Table(patient_table_data, colWidths=[150, 350])
    table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (0,-1), colors.whitesmoke)
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # Health data
    if data.health_data:
        elements.append(Paragraph("Patient Health Data", styles["Heading2"]))
        elements.append(Spacer(1, 10))
        health_rows = [[k.replace("_"," ").title(), str(v)] for k,v in data.health_data.items()]
        health_table = Table(health_rows, colWidths=[200, 300])
        health_table.setStyle(TableStyle([("GRID",(0,0),(-1,-1),0.5,colors.grey)]))
        elements.append(health_table)
        elements.append(Spacer(1, 20))

    # AI predictions (Dynamic table)
    elements.append(Paragraph("AI Screening Results", styles["Heading2"]))
    elements.append(Spacer(1, 10))

    # Get predictions safely
    pred = getattr(data.prediction, "combined_predictions", {}) or {}
    
    prediction_table_data = [["Condition", "Prediction", "Confidence", "Interpretation"]]
    missing_tests = []

    # DR Row
    if "dr" in pred:
        dr = pred["dr"]
        prediction_table_data.append([
            "Diabetic Retinopathy",
            dr.get("final_stage", "N/A"),
            f'{dr.get("confidence", 0)*100:.1f}%',
            dr.get("interpretation", "N/A")
        ])
    else:
        missing_tests.append("Diabetic Retinopathy")

    # DME row (if present)
    if "dme" in pred:
        dme = pred["dme"]
        prediction_table_data.append([
            "Diabetic Macular Edema",
            dme.get("final_prediction", "N/A"),
            f'{dme.get("confidence", 0)*100:.1f}%',
            dme.get("interpretation", "N/A")
        ])
    else:
        missing_tests.append("Diabetic Macular Edema")

    prediction_table = Table(prediction_table_data, colWidths=[150, 120, 80, 200])
    prediction_table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey)
    ]))

    elements.append(prediction_table)
    
    # Notify if some results are missing
    if missing_tests:
        elements.append(Spacer(1, 5))
        elements.append(Paragraph(f"Note: Results for {', '.join(missing_tests)} are not available.", styles["Normal"]))
    
    elements.append(Spacer(1, 25))

    # Images section
    elements.append(Paragraph("Diagnostic Images", styles["Heading2"]))
    elements.append(Spacer(1, 10))
    
    image_row = []
    if data.fundus_image_url and (fundus := download_image(data.fundus_image_url)):
        image_row.append(Image(fundus, width=2.5*inch, height=2.5*inch))
    if data.oct_image_url and (oct_img := download_image(data.oct_image_url)):
        image_row.append(Image(oct_img, width=2.5*inch, height=2.5*inch))

    if image_row:
        elements.append(Table([image_row]))

    elements.append(Spacer(1, 30))
    elements.append(Paragraph("This report was generated by an AI-assisted system. Please verify with a specialist.", styles["Italic"]))

    doc.build(elements)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=eye_report.pdf"}
    )