from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
import requests
from datetime import datetime

from schemas.save_prediction_schema import SavePredictionRequest

router = APIRouter(prefix="/report")

def download_image(url: str):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return BytesIO(response.content)
    except:
        pass
    return None

@router.post("/generate")
def generate_report(data: SavePredictionRequest):

    buffer = BytesIO()
    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=(595, 842),  # A4
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    elements = []

    # Title
    elements.append(Paragraph("Ophthalmology Screening Report", styles["Title"]))
    elements.append(Spacer(1, 20))

    # Patient Info
    patient_table_data = [
        ["Patient Name", data.patient_name],
        ["Patient ID", data.patient_id or "N/A"],
        ["Doctor ID", data.doctor_id],
        ["Generated On", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")]
    ]

    table = Table(patient_table_data, colWidths=[150, 350])
    table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (0,-1), colors.whitesmoke)
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # Health Data (optional)
    if data.health_data:
        elements.append(Paragraph("Patient Health Data", styles["Heading2"]))
        elements.append(Spacer(1,10))

        health_rows = []
        for k,v in data.health_data.items():
            health_rows.append([k.replace("_"," ").title(), str(v)])

        health_table = Table(health_rows, colWidths=[200,300])
        health_table.setStyle(TableStyle([
            ("GRID",(0,0),(-1,-1),0.5,colors.grey)
        ]))

        elements.append(health_table)
        elements.append(Spacer(1,20))

    # Predictions
    pred = data.prediction.combined_predictions

    elements.append(Paragraph("AI Screening Results", styles["Heading2"]))
    elements.append(Spacer(1,10))

    prediction_table_data = [
        ["Condition", "Prediction", "Confidence", "Interpretation"],
        [
            "Diabetic Retinopathy",
            pred["dr"]["final_stage"],
            f'{pred["dr"]["confidence"]*100:.1f}%',
            pred["dr"]["interpretation"]
        ],
        [
            "Diabetic Macular Edema",
            pred["dme"]["final_prediction"],
            f'{pred["dme"]["confidence"]*100:.1f}%',
            pred["dme"]["interpretation"]
        ]
    ]

    prediction_table = Table(prediction_table_data, colWidths=[150,120,80,200])
    prediction_table.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),0.5,colors.grey),
        ("BACKGROUND",(0,0),(-1,0),colors.lightgrey)
    ]))

    elements.append(prediction_table)
    elements.append(Spacer(1,25))

    # Images Section
    elements.append(Paragraph("Diagnostic Images", styles["Heading2"]))
    elements.append(Spacer(1,10))

    image_row = []

    if data.fundus_image_url:
        fundus = download_image(data.fundus_image_url)
        if fundus:
            image_row.append(Image(fundus, width=2.5*inch, height=2.5*inch))

    if data.oct_image_url:
        oct_img = download_image(data.oct_image_url)
        if oct_img:
            image_row.append(Image(oct_img, width=2.5*inch, height=2.5*inch))

    if image_row:
        img_table = Table([image_row])
        elements.append(img_table)

    elements.append(Spacer(1,30))

    # Footer Disclaimer
    elements.append(Paragraph(
        "This report was generated by an AI-assisted screening system and should be reviewed by a qualified ophthalmologist.",
        styles["Italic"]
    ))

    doc.build(elements)

    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=eye_report.pdf"}
    )